### ISSUE TITLE
Cannot access `package-list` in published Javadoc

### ISSUE THREAD

**Issue by KMGraf** [junit-team/junit5#1289]
## Bug Report for JUnit 4

`javadoc -link http://junit.org/junit4/javadoc/latest` (i.e. referring JUnit 4's Javadoc pages from 3rd-party Javadoc pages) no longer works because http://junit.org/junit4/javadoc/latest/package-list disappeared.

### Deliverables

- [x] See https://github.com/junit-team/junit5/issues/1289#issuecomment-364247470

## Bug Report for JUnit 5

An upgrade in the JDK used to generate Javadoc for JUnit 5 caused the `package-list` file to stop being published beginning with JUnit 5.2.

In the following list, the first number is the HTTP response code.

- *200*: https://junit.org/junit5/docs/5.1.0/api/package-list
- *404*: https://junit.org/junit5/docs/5.2.0/api/package-list
- *404*: https://junit.org/junit5/docs/current/api/package-list

### Deliverables

- [ ] Manually copy `element-list` to `package-list` for previously released versions of JUnit 5.
- [ ] Automate copying of `element-list` to `package-list` in the Gradle build for future versions of JUnit 5.

**Comment by sbrannen** [comment]
Please note that this is the issue tracker for JUnit 5 (not for JUnit 4).

Are you referring to a link to JUnit 4 from the JUnit 5 User Guide or the JavaDoc for JUnit 5?

If not, please open an issue against [JUnit 4](https://github.com/junit-team/junit4/issues).

**Comment by marcphilipp** [comment]
Related issue: https://github.com/junit-team/junit4/issues/1500

**Comment by marcphilipp** [comment]
I've disabled Cloudflare's Browser Integrity Check.

@KMGraf Can you please try again?

**Comment by marcphilipp** [comment]
Oh, have you tried using HTTPS?

**Comment by KMGraf** [comment]
I changed to https which alone did not help. But now after your change everything is ok again. Thank you for your quick response.

**Comment by sbrannen** [comment]
@onacit, that's because there is no `package-list` folder or file in that directory.

https://github.com/junit-team/junit5/tree/gh-pages/docs/current/api

Why are you trying to access that URL?

**Comment by sbrannen** [comment]
FYI: the new location for that `package-list` file is the following:

https://github.com/junit-team/junit5/blob/gh-pages/docs/current/api/element-list

Or this URL for the current "published" version:

https://junit.org/junit5/docs/current/api/element-list

**Comment by sbrannen** [comment]
Also, it appears you will need to use Java 10 to access the `element-list` file instead of the `package-list` file automatically.

This is explained here: https://stackoverflow.com/a/49498219/388980

**Comment by sbrannen** [comment]
The rationale for the change in the JDK is documented in this proposal:

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8191363

**Comment by sbrannen** [comment]
After further analysis, I have determined that an upgrade in the JDK used to generate Javadoc for JUnit 5 caused the `package-list` file to stop being published beginning with JUnit 5.2.

In the following list, the first number is the HTTP response code.

- *200*: https://junit.org/junit5/docs/5.1.0/api/package-list
- *404*: https://junit.org/junit5/docs/5.2.0/api/package-list
- *404*: https://junit.org/junit5/docs/current/api/package-list

**Comment by sbrannen** [comment]
I am reopening this issue in order to address the recently reported issue with `package-list` for JUnit 5. See previous comments.

**Comment by marcphilipp** [comment]
I've changed our build to copy `element-list` to `package-list` in dd68fbad1854ba349dde481116562224c2d284e3.

**Comment by sbrannen** [comment]
I manually copied `element-list` to `package-list` for all previously releases in 7e1cef4aad91bcd9d20de379dc6b55432c8e2947.

**Comment by sbrannen** [comment]
> I receive 404 from https://junit.org/junit5/docs/current/api/package-list.

@onacit, that should now work for you. Please let us know if it does not.

**Comment by jmccay-work** [comment]
I just downloaded the jars for 5.62 (Vintage and Jupiter) and 1.62 (Platform) from the link on the main page, and this is still an issue.  Is there any chance this bug will be fixed?  

I would like to mention the links on the JUnit 5 main page are to 5.6.1 for Jupiter and Vintage and the platform is linked to 1.6.1 even though they are labeled as 5.6.2 and 1.6.2.

**Comment by sormuras** [comment]
> I would like to mention the links on the JUnit 5 main page are to 5.6.1 for Jupiter and Vintage and the platform is linked to 1.6.1 even though they are labeled as 5.6.2 and 1.6.2.

Fixed via https://github.com/junit-team/junit5/commit/989dff30872fe9a77e38b07a0e4c1acdbc4672e5 -- thanks for the heads up.

**Comment by sormuras** [comment]
> I just downloaded the jars for 5.62 (Vintage and Jupiter) and 1.62 (Platform) from the link on the main page, and this is still an issue. Is there any chance this bug will be fixed?

fup2 #2278
