### ISSUE TITLE
Gradle "clean build" failure due to deprecated "junit-jupiter-migration-support"

### ISSUE THREAD

**Issue by mkobit** [junit-team/junit5#894]
Tried to build master on my Mac but `:platform-tests:junitPlatformTest` failed.

```
Failures (1):
  JUnit Jupiter:AutomaticModuleNameTests:automaticModuleName(String):[3] junit-jupiter-migration-support
    MethodSource [className = 'org.junit.AutomaticModuleNameTests', methodName = 'automaticModuleName', methodParameterTypes = 'java.lang.String']
    => org.opentest4j.AssertionFailedError: `Automatic-Module-Name` not found in manifest of JAR: ../junit-jupiter-migration-support/build/libs/junit-jupiter-migration-support-5.0.0-SNAPSHOT.jar ==> expected: not <null>
```

* At SHA - 155a2dd995e98ad7ce8e6615a74e127598a0173b
* Build Scan: https://scans.gradle.com/s/i7fnzauqooo36#summary

## Reason
> `junit-jupiter-migration-support` was renamed to `junit-jupiter-migrationsupport` and the directory is still present in my repository.

See https://github.com/junit-team/junit5/commit/a19e6ee83bace8554c761ff20d2a9a0cbcd1f6ec for details

## Solution
Manually remove `junit-jupiter-migration-support` or use `git clean -d`

**Comment by sormuras** [comment]
Known issue, working on it... see https://github.com/junit-team/junit5/commit/cadce8a9ad068e6e10f40967fd25d5fd3946afcb

Try a `gradlew clean build` to force all jars to be rebuild.

**Comment by sormuras** [comment]
Adding following lines to `platform-tests/platform-tests.gradle` seems to solve the issue.
```
junitPlatformTest.dependsOn(
        project(':junit-jupiter-migrationsupport').jar,
        project(':junit-platform-gradle-plugin').jar,
        project(':junit-platform-surefire-provider').jar
)
```

I guess, there's a more Gradle-y way to solve it.

**Comment by sormuras** [comment]
Addressed via commit https://github.com/junit-team/junit5/commit/58d5c34876992c3833016b82f0b5dbdd4cf3ff05

Leaving this issue open for review.

**Comment by mkobit** [comment]
Still seeing same issue in 58d5c34876

* Another scan at https://gradle.com/s/e7xjw5b6rv2xwg will hopefully give some more insight, I'm trying to take a look at it now

**Comment by mkobit** [comment]
Oh! Never mind! I think it was because `junit-jupiter-migration-support` was renamed to `junit-jupiter-migrationsupport` and the directory is still present in my repository.

**Comment by sormuras** [comment]
Closing this issue.

Any Gradle build configuration improvements should go into a new issue.
